#!/usr/bin/env python

import time
import sys
import argparse

from fpga_lib.driver import driver

import bind_lmk

parser = argparse.ArgumentParser(description = 'Read/write raw registers')
parser.add_argument(
    '-a', dest = 'addr', default = 0,
    help = 'Set physical address of card.  If not specified then card 1')
parser.add_argument(
    'count', default = 1, nargs = '?', type = int,
    help = 'Number of samples to show')
args = parser.parse_args()


top = bind_lmk.open(args.addr)


def print_freqs():
    while not top.EVENTS.COUNT_UPDATE:
        time.sleep(0.01)
    for freq_reg in top.CLOCK_FREQ:
        print(freq_reg._value, end = '  ')
    print()

count = args.count
try:
    if count > 0:
        for n in range(count):
            print_freqs()
    else:
        while True:
            print_freqs()
except KeyboardInterrupt:
    pass
