#!/usr/bin/env python

import os
import numpy
import time

from fpga_lib.driver import driver

from bind_lmk import top, lmk
import setup_lmk


# Clock frequencies in order:
#   CK on CLKOUT14
#   WCK on CLKOUT8
#   WCK on CLKOUT10
def print_freqs():
    while not top.EVENTS.COUNT_UPDATE:
        time.sleep(0.01)
    for i in range(3):
        print(top.CLOCK_FREQ[i]._value, end = '  ')
    print()


print_freqs()

setup_lmk.setup_sync(lmk)

print_freqs()

lmk.GLOBAL_SYNC = 1

print_freqs()

# top.CONFIG._write_fields_rw(LMK_SELECT = 0, LMK_SYNC = 1)

# print_freqs()
# print_freqs()

# top.CONFIG._write_fields_rw(LMK_SELECT = 0, LMK_SYNC = 0)

print_freqs()

lmk.GLOBAL_SYNC = 0

print_freqs()
print_freqs()
