# Top level makefile for building FPGA

# Boilerplate top level call.  Must include the top level CONFIG
# Once the build directory has been created this Makefile will be invoked again
# with PROJECT_TOP set to this directory.
include ../CONFIG
include $(FPGA_COMMON)/makefiles/Makefile.fpga
