#!/usr/bin/env bash

cd "$(dirname "$0")"  &&

./enable-ctrl -d  &&
./reset-ck  &&
./reset-sg  &&
./train-ca -q  &&
./read-vid -q  &&
./config-sg  &&
./train-read -frR -sv -q  &&
./train-write -frR -sv -q  &&
./enable-ctrl -e
