#!/usr/bin/env python

import os

import bind_lmk


top = bind_lmk.open()

def read_lmk(addr, sel=0):
    top.LMK04616._write_fields_wo(ADDRESS = addr, R_WN = 1, SELECT = sel)
    return top.LMK04616.DATA

# # Force a reset of the selected device
# top.CONFIG._write_fields_rw(LMK_SELECT = 0, LMK_RESET = 1)
# # The reset time is 25 n
# top.CONFIG._write_fields_rw(LMK_SELECT = 0, LMK_RESET = 0)

for line in open('reg-list').readlines():
    addr = int(line, 0)
    lmk = read_lmk(addr)
    print('PLL[%03X] => %02X' % (addr, lmk))

# print('%02X' % read_lmk(0x0c))
