#!/usr/bin/env python

import os

from fpga_lib.driver import driver

here = os.path.dirname(__file__)
register_defines = os.path.join(here, '../vhd', 'register_defines.in')

raw_regs = driver.RawRegisters('ifc_1412-lmk', 0)
regs = driver.Registers(raw_regs, register_defines)
top = regs.TOP

def read_lmk(addr, sel=0):
    top.LMK04616._write_fields_wo(ADDRESS = addr, R_WN = 1, SELECT = sel)
    return top.LMK04616.DATA

# # Force a reset of the selected device
# top.CONFIG._write_fields_rw(LMK_SELECT = 0, LMK_RESET = 1)
# # The reset time is 25 n
# top.CONFIG._write_fields_rw(LMK_SELECT = 0, LMK_RESET = 0)

for line in open('reg-list').readlines():
    addr = int(line, 0)
    lmk = read_lmk(addr)
    print('PLL[%03X] => %02X' % (addr, lmk))

# print('%02X' % read_lmk(0x0c))
