#!/usr/bin/env python

from registers import read_delay

print('DQ RX IDELAY')
for n in range(0, 64, 16):
    print('%2d' % n, end = ': ')
    for i in range(16):
        print(' %3d' % read_delay(n + i), end = '')
    print()
print('DQ TX ODELAY')
for n in range(0, 64, 16):
    print('%2d' % n, end = ': ')
    for i in range(16):
        print(' %3d' % read_delay(64 + n + i), end = '')
    print()
print('DBI IDELAY/ODELAY')
print('    ', end = '')
for i in range(16):
    print(' %3d' % read_delay(208 + i), end = '')
print()
print('EDC IDELAY')
print('    ', end = '')
for i in range(8):
    print(' %3d' % read_delay(224 + i), end = '')
print()
