#!/usr/bin/env python

# Brings SG out of reset

import time

from registers import sg


# Configuration settings for SG1 and SG2
SG1_CA = 0b111_1_00_00_00       # SG1: all inputs high impedance
SG2_CA = 0b111_1_11_11_11       # SG2: CK @ 60 Ohm, CA @ 120 Ohm
NOP = (0b11_11111111, 0b11_11111111)


# Set CA to requested value
def set_ca(value, cke_n):
    sg.COMMAND._write_fields_wo(START_WRITE = 1)
    sg.CA._write_fields_wo(
        RISING = value[0], FALLING = value[0],
        CA3 = 0, CKE_N = cke_n, OUTPUT_ENABLE = 0)
    sg.COMMAND._write_fields_wo(EXCHANGE = 1)


assert sg.STATUS.CK_OK, 'CK is not running and enabled'

if sg.CONFIG.SG_RESET_N != 3:
    print('Resetting SG ram')
    sg.CONFIG.SG_RESET_N = 0
    time.sleep(0.1)


# During reset need to ensure data is sent as requested
sg.CONFIG.ENABLE_CABI = 0

time.sleep(0.01)
set_ca((SG1_CA, SG1_CA), 1)
sg.CONFIG.SG_RESET_N = 1

time.sleep(0.01)
set_ca((SG2_CA, SG2_CA), 1)
sg.CONFIG.SG_RESET_N = 3

# Now allow EDC_T to be driven by SG RAM
sg.CONFIG.EDC_T = 1

# Complete initialisation by sending NOP and pulling CKEn low
set_ca(NOP, 0)
