#!/usr/bin/env python

import numpy

from registers import driver, regs

sg = regs.SYS.GDDR6

print(sg.STATUS)
assert not sg.STATUS.CK_OK, 'Already initialised'

print(sg.CONFIG)
sg.CONFIG.CK_RESET_N = 1
print(sg.STATUS)
