#!/usr/bin/env python

import time
import sys

from registers import regs, sg
from fpga_lib.boards import ifc_1412

# read/write/reset bindings for SYS LMK
class LMK:
    def __init__(self, top):
        self.__top = top

    def write(self, reg, value):
        self.__top.LMK04616._write_fields_wo(
            ADDRESS = reg, R_WN = 0, SELECT = 0, DATA = value)

    def read(self, reg):
        self.__top.LMK04616._write_fields_wo(
            ADDRESS = reg, R_WN = 1, SELECT = 0)
        return self.__top.LMK04616.DATA

    def reset(self, duration = 0.01):
        self.__top.CONFIG._write_fields_rw(LMK_SELECT = 0)
        self.__top.CONFIG._write_fields_rw(LMK_SELECT = 0, LMK_RESET = 1)
        time.sleep(duration)
        self.__top.CONFIG._write_fields_rw(LMK_SELECT = 0, LMK_RESET = 0)

top = regs.SYS
lmk = LMK(top)

if sys.argv[1:]:
    config = sys.argv[1]
else:
    config = '250'
lmk = ifc_1412.setup_sys_lmk(lmk, config = config)

# Give the system time to lock
time.sleep(0.01)
print(
    'Locked' if lmk.PLL2_LCK_DET else 'Unlocked',
    ', Status =', top.STATUS.LMK_STATUS)
