#!/usr/bin/env python

# CA training

import time
import numpy

from registers import sg

from gddr6_lib.commands import *
from gddr6_lib import exchange
from gddr6_lib.display import *


assert sg.STATUS.CK_OK, 'CK is not running and enabled'
assert sg.CONFIG.SG_RESET_N == 3, 'SG RAM in reset'

exchange = exchange._Exchange(sg)


# First test with CABI off
sg.CONFIG.ENABLE_CABI = 0
sg.CONFIG.CAPTURE_DBI = 1


# Some CAT patterns
PATTERN1 = (0x155, 0x2AA)
PATTERN2 = (0x2AA, 0x155)
ZEROS = (0, 0)

exchange.command(CAT_PASS1)
exchange.delay(10)
# exchange.command(PATTERN1)
exchange.command(PATTERN1, 1)
exchange.delay(2)
exchange.command(PATTERN2, 1)
exchange.delay(2)
exchange.command(PATTERN1, 1)
exchange.delay(2)
exchange.command(PATTERN2, 1)
exchange.delay(1)
exchange.command(ZEROS)
exchange.command(ZEROS, 1)
exchange.delay(2)
exchange.command(NOP, 1)
exchange.command(CAT_EXIT, 1)
exchange.delay(15)
data = exchange.run()
edc_in, edc_out = exchange.read_edc()

print_condensed_data_edc(data, edc_in, edc_out)
