# Top level makefile for building FPGA

# PROJECT_NAME = test-regs

# Boilerplate top level call.  Must include the top level CONFIG
# Once the build directory has been created this Makefile will be invoked again
# with PROJECT_TOP set to this directory.
ifndef PROJECT_TOP
include ../CONFIG
include $(FPGA_COMMON)/makefiles/Makefile.fpga
else


endif
