#!/usr/bin/env python

import argparse

from ifc_lib.gddr6_lib import setup

import bind_ifc_1412


def parse_args():
    parser = argparse.ArgumentParser(
        description = 'Check and configure controller')
    actions = parser.add_mutually_exclusive_group()
    actions.add_argument('-e', '--enable', action = 'store_true',
        help = 'Enable controller')
    actions.add_argument('-d', '--disable', action = 'store_true',
        help = 'Disable controller')
    parser.add_argument('-p', '--priority',
        choices = ['round-robin', 'read', 'write'],
        help = 'Set read/write priority')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()
    _, sg = bind_ifc_1412.open()

    if args.enable:
        setup.enable_ctrl(sg)
    elif args.disable:
        setup.disable_ctrl(sg)

    if args.priority is not None:
        setup.set_ctrl_priority(sg,
            args.priority == 'round-robin',
            args.priority == 'write')

main()
