#!/usr/bin/env python

# Read training

import argparse
import time
import numpy

import bind_ifc_1412
from ifc_lib.gddr6_lib.commands import *
from ifc_lib.gddr6_lib.exchange import _Exchange, Stream
from ifc_lib.gddr6_lib.display import *
from ifc_lib.gddr6_lib.delays import set_idelay, set_ibitslip
from ifc_lib.gddr6_lib import setup



parser = argparse.ArgumentParser()
parser.add_argument('-a', '--address', default = 0)
parser.add_argument('-L', '--no_load', action = 'store_true')
parser.add_argument('-s', '--sweep', action = 'store_true')
parser.add_argument('-c', '--channel', default = 0, type = int)
parser.add_argument('-f', '--find_bitslip', action = 'store_true')
parser.add_argument('-B', '--set_bitslip', type = int)
parser.add_argument('-r', '--reset_bitslip', action = 'store_true')
parser.add_argument('-R', '--reset_idelay', action = 'store_true')
parser.add_argument('-v', '--validate', action = 'store_true')
parser.add_argument('-x', '--exchange', action = 'store_true')
parser.add_argument('-q', '--quiet', action = 'count', default = 0)
parser.add_argument('--report', type = str)
args = parser.parse_args()


_, sg = bind_ifc_1412.open(args.address)
setup.check_sg_ready(sg)



sg.CONFIG._write_fields_rw(
    # Can't have controller in charge
    ENABLE_CONTROL = 0,
    ENABLE_REFRESH = 0,
    ENABLE_AXI = 0,
    # Send commands unmodified
    ENABLE_CABI = 0,
    # Want to disable DBI for reception
    ENABLE_DBI = 0,
    # Ensure DBI register captures DBI
    CAPTURE_EDC_OUT = 0)


exchange = _Exchange(sg)
stream = Stream(exchange, 4)    # tLTLTR is minimum LDFF interval

test_patterns = [0xCCA0, 0x5500, 0x33CC, 0x1248, 0x5555, 0x0055]


def load_pattern(pattern):
    for b in range(16):
        bits = 0x3FF if (pattern >> b) & 1 else 0
        stream.command(LDFF(b, bits))

# Loads the given test pattern array
def load_patterns(test_patterns):
    exchange.reset()
    for pattern in test_patterns:
        load_pattern(pattern)
    exchange.exchange()

# Read test pattern
def read_test():
    exchange.reset()
    exchange.command(PREab)
    exchange.delay(4)
    exchange.command(REFab)
    exchange.delay(4)
    for i in range(6):
        exchange.command(RDTR)
        exchange.delay(1)
    exchange.delay(24)
    exchange.exchange()
    data = exchange.read_data()
    dbi, edc = exchange.read_dbi_edc()
    return (data, dbi, edc)

def dummy_exchange():
    exchange.reset()
    exchange.delay(46)
    exchange.exchange()
    data = exchange.read_data()
    dbi, edc = exchange.read_dbi_edc()
    return (data, dbi, edc)
# read_test = dummy_exchange


if not args.no_load:
    # First load our test pattern if required
    load_patterns(test_patterns)

if args.set_bitslip is not None:
    for n in range(80):
        set_ibitslip(sg, n, args.set_bitslip)
elif args.reset_bitslip:
    for n in range(80):
        set_ibitslip(sg, n, 0)
if args.reset_idelay:
    for n in range(80):
        set_idelay(sg, n, 0)

data, dbi, edc = read_test()

if args.exchange and not args.quiet:
    print_condensed_data_edc(data, dbi, edc, offset = 29)


def print_bits(offset, bytes):
    print('%2d' % offset, ' '.join(f'{byte:08b}'[::-1] for byte in bytes))

def show_channel(data, channel):
    for n in range(0, 16):
        ix = n + 16 * channel
        print_bits(ix, data[:, ix])

def extend(range):
    return numpy.s_[range.start-1 : range.stop + 1]



data_offset = 31
data_length = 12
data_range = numpy.s_[data_offset:data_offset + data_length]
edc_range = numpy.s_[data_offset+1:data_offset + 1 + data_length]


if not args.quiet:
    print('Data:')
    show_channel(data[extend(data_range)], args.channel)
    print('DBI:')
    for ix in range(8):
        print_bits(ix, dbi[extend(data_range), ix])
    print('EDC:')
    for ix in range(8):
        print_bits(ix, edc[extend(edc_range), ix])


def show_match(match):
    # Convert array of booleans into a string of 0 or 1
    show = ''.join('1' if m else '0' for m in match)
    # Split the string into four groups of 16 and two of 8 for ease of display
    splits = [0, 16, 32, 48, 64, 72, 80]
    return ' '.join(show[l:r] for l, r in zip(splits[:-1], splits[1:]))


def match_data(data, dbi, edc):
    data = data[data_range]
    dbi = dbi[data_range]
    edc = edc[edc_range]
    data = numpy.concatenate((data, dbi, edc), axis = 1)
    pattern = numpy.array(test_patterns, dtype = 'uint16').view('uint8')
    return (data == pattern[:, None]).all(0)

if not args.quiet:
    print(show_match(match_data(data, dbi, edc)))


def set_idelays(delays):
    # Ensure a constant behaves like an array
    delays = delays + numpy.zeros(80, dtype = numpy.int64)
    for a, d in zip(range(80), delays):
        set_idelay(sg, a, d)


def sweep_delays(max_delay):
    matches = numpy.zeros((max_delay, 80), dtype = numpy.bool)
    for delay in range(max_delay):
        set_idelays(delay)
        data, dbi, edc = read_test()
        matches[delay] = match_data(data, dbi, edc)
    return matches


# Returns a list of intervals as a list of tuples    (length, mid-point)
def find_intervals(scan):
    # This is kind of tricksy: we convert the array of bools scan into integers,
    # and then use diff() and where() to find the start and end of the window,
    # which is defined by a contiguous block of True.
    diffs = numpy.diff(numpy.int8(numpy.concatenate(([0], scan, [0]))))
    starts = numpy.where(diffs == 1)[0]
    ends = numpy.where(diffs == -1)[0]
    return [
        (end - start, (start + end) // 2)
        for start, end in zip(starts, ends)]

def find_longest_interval(intervals):
    if len(intervals) > 1 and not args.quiet:
        print('intervals:', intervals)
    best = intervals[0]
    for interval in intervals[1:]:
        if interval[0] > best[0]:
            best = interval
    return best

def find_eyes(matches):
    best = [
        find_longest_interval(find_intervals(scan))
        for scan in matches.T]
    lengths = numpy.array([l for l, _ in best])
    centres = [c for _, c in best]
    if not args.quiet:
        print(list(lengths))
        print(centres)
    return (centres, lengths)


def count_offset(byte):
    for n in range(8):
        if byte == 0:
            return n
        else:
            byte = (byte << 1) & 0xFF
    assert False, 'Unable to find bitslip offset'


def create_report(report, bitslips, delays, windows):
    with open(report, 'w') as report:
        def print_array(array):
            print(' '.join(map(str, array)), file = report)
        print_array(bitslips)
        print_array(delays)
        print_array(windows)


if args.find_bitslip:
    # Search for best bitslip
    data, dbi, edc = read_test()
    data = numpy.concatenate(
        (data[data_offset + 11], dbi[data_offset + 11], edc[data_offset + 12]))
    offsets = [count_offset(b) for b in data]
    if not args.quiet:
        print(offsets)
    bitslips = [max(0, o - 1) for o in offsets]
    for n, b in enumerate(bitslips):
        set_ibitslip(sg, n, b)


if args.sweep:
    matches = sweep_delays(500)
    if matches.any(axis = 0).all():
        delays, windows = find_eyes(matches)
        if args.quiet < 2:
            print('Read window:', windows.min(), 'to', windows.max())
        set_idelays(delays)
    elif args.sweep:
        print('Not enough data eyes found')
        print(matches)

if args.report:
    create_report(args.report, bitslips, delays, windows)


def check_read_data():
    # Run scan repeatedly until killed or there is an error
    data, dbi, edc = read_test()
    matches = match_data(data, dbi, edc)
    assert matches.all(), 'Match error: %s' % matches

if args.validate:
    data, dbi, edc = read_test()
    match = match_data(data, dbi, edc)
    if not args.quiet or not match.all():
        print(show_match(match))
    assert match.all(), 'Read training failed'
