#!/usr/bin/env python

import argparse

from ifc_lib import defs_path
from fpga_lib.driver import driver
from ifc_lib import mailbox as mb


class Registers(driver.RawRegisters):
    NAME = 'ifc_1412-mailbox'

    def __init__(self, address = 0):
        super().__init__(self.NAME, address)
        register_defines = defs_path.register_defines(__file__)
        mailbox_defines = defs_path.module_defines('mailbox')
        self.make_registers('TOP', None, mailbox_defines, register_defines)

def open(addr = 0):
    regs = Registers(addr)
    return regs.TOP.MAILBOX


def to_int(s):
    return int(s, 0)

def parse_args():
    parser = argparse.ArgumentParser(description = 'Read/write raw registers')
    parser.add_argument(
        '-a', dest = 'address', default = 0,
        help = 'Set physical address of card.  If not specified then card 0')

    subparsers = parser.add_subparsers(
        dest = 'select',
        help = 'Select read or write, use -h after selection for specific help')

    read_parser = subparsers.add_parser('read',
        description = 'Read from mailbox')
    read_parser.add_argument(
        'mb_address', type = to_int, help = 'Address to read from')

    write_parser = subparsers.add_parser('write',
        description = 'Write to mailbox')
    write_parser.add_argument(
        'mb_address', type = to_int, help = 'Address to write to')
    write_parser.add_argument(
        'values', type = to_int, nargs = '+',
        help = 'Values to write')

    slot_parser = subparsers.add_parser('slot',
        description = 'Show slot number')

    identity_parser = subparsers.add_parser('show',
        description = 'Return identity')
    identity_parser.add_argument(
        'message', choices = ['mmc', 'rtm', 'payload'],
        help = 'Select message to show')

    args = parser.parse_args()
    if args.select is None:
        parser.error("Must specify action")
    return args



def main():
    args = parse_args()
    mailbox = open(args.address)

    if args.select == 'read':
        result = mb.read_mailbox(mailbox, args.mb_address)
        print(f'MB[{args.mb_address}]: {result}')
    elif args.select == 'write':
        mb.write_mailbox(mailbox, args.mb_address, args.values)
    elif args.select == 'slot':
        print(mb.read_slot(mailbox))
    elif args.select == 'show':
        print(mb.read_message(mailbox, args.message).format())

main()
